(function() {var implementors = {};
implementors["winreg"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"winreg/struct.RegKeyMetadata.html\" title=\"struct winreg::RegKeyMetadata\">RegKeyMetadata</a>",synthetic:true,types:["winreg::RegKeyMetadata"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"winreg/struct.RegValue.html\" title=\"struct winreg::RegValue\">RegValue</a>",synthetic:true,types:["winreg::RegValue"]},{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"winreg/struct.RegKey.html\" title=\"struct winreg::RegKey\">RegKey</a>",synthetic:true,types:["winreg::RegKey"]},{text:"impl&lt;'key&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"winreg/struct.EnumKeys.html\" title=\"struct winreg::EnumKeys\">EnumKeys</a>&lt;'key&gt;",synthetic:true,types:["winreg::EnumKeys"]},{text:"impl&lt;'key&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"winreg/struct.EnumValues.html\" title=\"struct winreg::EnumValues\">EnumValues</a>&lt;'key&gt;",synthetic:true,types:["winreg::EnumValues"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"enum\" href=\"winreg/enums/enum.RegType.html\" title=\"enum winreg::enums::RegType\">RegType</a>",synthetic:true,types:["winreg::enums::RegType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"enum\" href=\"winreg/enums/enum.RegDisposition.html\" title=\"enum winreg::enums::RegDisposition\">RegDisposition</a>",synthetic:true,types:["winreg::enums::RegDisposition"]},{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"winreg/transaction/struct.Transaction.html\" title=\"struct winreg::transaction::Transaction\">Transaction</a>",synthetic:true,types:["winreg::transaction::Transaction"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
