(function() {var implementors = {};
implementors["winreg"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"winreg/enums/enum.RegType.html\" title=\"enum winreg::enums::RegType\">RegType</a>",synthetic:false,types:["winreg::enums::RegType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"winreg/enums/enum.RegDisposition.html\" title=\"enum winreg::enums::RegDisposition\">RegDisposition</a>",synthetic:false,types:["winreg::enums::RegDisposition"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"winreg/transaction/struct.Transaction.html\" title=\"struct winreg::transaction::Transaction\">Transaction</a>",synthetic:false,types:["winreg::transaction::Transaction"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"winreg/struct.RegKeyMetadata.html\" title=\"struct winreg::RegKeyMetadata\">RegKeyMetadata</a>",synthetic:false,types:["winreg::RegKeyMetadata"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"winreg/struct.RegValue.html\" title=\"struct winreg::RegValue\">RegValue</a>",synthetic:false,types:["winreg::RegValue"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"winreg/struct.RegKey.html\" title=\"struct winreg::RegKey\">RegKey</a>",synthetic:false,types:["winreg::RegKey"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
